import { getMockDataset } from "@/lib/mock-selectors";

import type { TaskCardSeed } from "@/lib/task-cards/types";

const dataset = getMockDataset();

function accountThreadId(accountId: string) {
  return dataset.accountThreads.find((thread) => thread.accountId === accountId)?.id ?? `thread-${accountId}`;
}

const accountThreadIds = {
  zifei: accountThreadId("acc-real-1"),
  dakewan: accountThreadId("acc-real-2"),
  dachen: accountThreadId("acc-real-5"),
  newstar: accountThreadId("acc-real-6"),
  xuanhe: accountThreadId("acc-3"),
};

export const taskCardSeed: TaskCardSeed = {
  cards: [
    {
      id: "rep-card-1",
      level: "rep",
      cardType: "rep_execution",
      escalationCategory: null,
      upgradeReason: null,
      title: "广州紫菲网络科技有限公司需要 1 周内二访验证试点切口",
      summary:
        "杨文星已经从一访里收敛出最现实的推进方向：先验证 VOD 聚合 API、云成本和试点边界，而不是直接谈整体替换。",
      recommendedAction: "今天把二访阵容、试点问题清单和材料框架发给刘建明确认。",
      whyNow: "紫菲的窗口就在 1 周内，如果这次不把二访锁死，最清晰的切口会重新散掉。",
      impactLabel: "当前判断",
      impactValue: "1 周内完成二访并验证试点切口",
      ownerRole: "rep",
      ownerName: "杨文星",
      targetRole: null,
      targetName: null,
      status: "confirmed",
      dueLabel: "1 周内",
      priority: 99,
      confidence: 0.82,
      dataFreshness: "fresh",
      coverage: 0.82,
      trustNote: "结论来自真实会议转写与会后跟进，但正式公司名只在紫菲这条线上能被原始材料和公开信息较高置信度支撑。",
      reasonItems: [
        "原始材料直接出现葫芦娃 IP，说明客户仍在围绕既有 IP 找增量切口。",
        "会后已出现 1 周内组织二访的窗口。",
      ],
      lineageId: "lineage-zifei",
      sourceKind: "meeting",
      sourceIds: ["meeting-real-1"],
      evidenceIds: ["evidence-real-1"],
      accountIds: ["acc-real-1"],
      dealIds: ["deal-real-1"],
      meetingIds: ["meeting-real-1"],
      isVisible: true,
      canAssign: false,
      canEscalate: true,
      canRevoke: false,
      canDrillDown: true,
      availableActions: [
        { kind: "confirm", label: "确认建议", nextStatus: "confirmed" },
        { kind: "report", label: "提交汇报", nextStatus: "reported" },
      ],
    },
    {
      id: "rep-card-2",
      level: "rep",
      cardType: "rep_execution",
      escalationCategory: null,
      upgradeReason: null,
      title: "玄河网络必须在 48 小时内重建高层赞助",
      summary:
        "刘建明已正式下发任务：先把 sponsor 和采购拉回同一张桌子，再决定这条后期 deal 是否还值得继续按当前 forecast 推进。",
      recommendedAction: "48 小时内锁定一场带 CRO 参加的重启会议，并补齐采购顾虑摘要。",
      whyNow: "这条后期商机已经进入信任收缩期，再拖会直接影响主管是否继续给资源。",
      impactLabel: "影响金额",
      impactValue: "CNY 4,080,000",
      ownerRole: "rep",
      ownerName: "顾景行",
      targetRole: null,
      targetName: null,
      status: "received",
      dueLabel: "48 小时内",
      priority: 86,
      confidence: 0.62,
      dataFreshness: "stale",
      coverage: 0.58,
      trustNote: "会议纪要足够清楚，但 CRM 同步过期，判断可信度已经被拉低。",
      reasonItems: [
        "客户明确表示高层赞助人与采购仍未真正对齐。",
        "最近一次会议没有形成带日期的下一步。",
      ],
      lineageId: "lineage-xuanhe",
      sourceKind: "manager_assignment",
      sourceIds: ["manager-card-2"],
      evidenceIds: ["evidence-1", "evidence-2"],
      accountIds: ["acc-3"],
      dealIds: ["deal-2"],
      meetingIds: ["meeting-2"],
      isVisible: true,
      canAssign: false,
      canEscalate: true,
      canRevoke: false,
      canDrillDown: true,
      availableActions: [
        { kind: "accept", label: "接受任务", nextStatus: "accepted" },
        { kind: "report", label: "提交汇报", nextStatus: "reported" },
      ],
    },
    {
      id: "rep-card-3",
      level: "rep",
      cardType: "rep_execution",
      escalationCategory: null,
      upgradeReason: null,
      title: "广州大臣信息科技有限公司需要先锁定月底广州会阵容",
      summary:
        "客户认可产品能力，但真正能不能推进，取决于月底广州会能否把老板和技术负责人一起拉进小游戏线试点判断。",
      recommendedAction: "今天先把月底广州会的候选时间、参会角色和只谈小游戏线的议题发出。",
      whyNow: "如果继续泛泛聊整套后台替换，这条线会停在“认可产品但不动”的状态。",
      impactLabel: "当前目标",
      impactValue: "把月底广州会收敛成小游戏线试点判断",
      ownerRole: "rep",
      ownerName: "杨文星",
      targetRole: null,
      targetName: null,
      status: "suggested",
      dueLabel: "今天内",
      priority: 80,
      confidence: 0.71,
      dataFreshness: "fresh",
      coverage: 0.75,
      trustNote: "会议事实较完整，但正式公司名来自内部映射，适合 demo，不应误写成录音直出的硬事实。",
      reasonItems: [
        "客户已经明确表达后台能力被认可。",
        "真正阻力是组织替换成本和老板是否在场。",
      ],
      lineageId: "lineage-dachen-pricing",
      sourceKind: "meeting",
      sourceIds: ["meeting-real-5"],
      evidenceIds: ["evidence-real-5"],
      accountIds: ["acc-real-5"],
      dealIds: ["deal-real-5"],
      meetingIds: ["meeting-real-5"],
      isVisible: true,
      canAssign: false,
      canEscalate: true,
      canRevoke: false,
      canDrillDown: true,
      availableActions: [
        { kind: "confirm", label: "确认建议", nextStatus: "confirmed" },
        { kind: "report", label: "提交汇报", nextStatus: "reported" },
      ],
    },
    {
      id: "rep-card-4",
      level: "rep",
      cardType: "rep_execution",
      escalationCategory: null,
      upgradeReason: null,
      title: "曜石游戏先补齐实施边界再继续报价",
      summary: "客户有兴趣，但会议缺少完整转录，当前判断不能直接当成强需求成立。",
      recommendedAction: "补一次 20 分钟澄清会，先把实施工作量与客户投入边界问清。",
      whyNow: "继续报价只会放大误判，先补齐事实比推进速度更重要。",
      impactLabel: "当前金额",
      impactValue: "CNY 220,000",
      ownerRole: "rep",
      ownerName: "许明澈",
      targetRole: null,
      targetName: null,
      status: "suggested",
      dueLabel: "本周内",
      priority: 54,
      confidence: 0.54,
      dataFreshness: "missing",
      coverage: 0.37,
      trustNote: "缺少完整转录和稳定邮件上下文，这条建议必须谨慎采纳。",
      reasonItems: [
        "客户最先追问的是实施工作量，而不是采购细节。",
        "会后没有补齐完整纪要和下一步责任归属。",
      ],
      lineageId: "lineage-yaoshi",
      sourceKind: "meeting",
      sourceIds: ["meeting-5"],
      evidenceIds: ["evidence-3"],
      accountIds: ["acc-5"],
      dealIds: ["deal-5"],
      meetingIds: ["meeting-5"],
      isVisible: true,
      canAssign: false,
      canEscalate: false,
      canRevoke: false,
      canDrillDown: true,
      availableActions: [
        { kind: "confirm", label: "确认建议", nextStatus: "confirmed" },
        { kind: "report", label: "提交汇报", nextStatus: "reported" },
      ],
    },
    {
      id: "manager-card-1",
      level: "manager",
      cardType: "manager_intervention",
      escalationCategory: null,
      upgradeReason: null,
      title: "刘建明需要帮杨文星锁定紫菲二访阵容",
      summary:
        "杨文星已经判断紫菲最现实的切口在二访验证。主管当前要做的不是再看摘要，而是把谁参加二访、带什么材料、要验证什么问题锁死。",
      recommendedAction: "今天确认杨文星的二访阵容，并决定是否预留售前资源。",
      whyNow: "紫菲这条线的价值在于试点窗口清晰，但窗口很短；如果不在主管层收口，会重新退回泛泛交流。",
      impactLabel: "主管动作",
      impactValue: "锁定二访阵容 / 材料 / 问题清单",
      ownerRole: "manager",
      ownerName: "刘建明",
      targetRole: "rep",
      targetName: "杨文星",
      status: "reviewed",
      dueLabel: "今天内",
      priority: 97,
      confidence: 0.84,
      dataFreshness: "fresh",
      coverage: 0.82,
      trustNote: "公司名来源和会后判断已拆开显示，主管看到的是编排动作，不是原始会议逐字稿。",
      reasonItems: [
        "紫菲的一访已明确不是整体替换，而是二访验证切口。",
        "杨文星已经把最关键的问题从会里提炼出来。",
      ],
      lineageId: "lineage-zifei",
      sourceKind: "report_snapshot",
      sourceIds: ["rep-report-rep-2", "meeting-real-1"],
      evidenceIds: ["evidence-real-1"],
      accountIds: ["acc-real-1"],
      dealIds: ["deal-real-1"],
      meetingIds: ["meeting-real-1"],
      isVisible: true,
      canAssign: true,
      canEscalate: true,
      canRevoke: false,
      canDrillDown: true,
      availableActions: [
        { kind: "escalate", label: "升级 CEO", nextStatus: "escalated" },
      ],
    },
    {
      id: "manager-card-2",
      level: "manager",
      cardType: "manager_intervention",
      escalationCategory: null,
      upgradeReason: null,
      title: "玄河网络需要战略客户组 48 小时干预",
      summary:
        "顾景行的会后汇报已经明确：真正阻力不是报价，而是 sponsor 和采购没有重新对齐。",
      recommendedAction: "保留这张下游任务卡，或在判断失误时直接撤销。",
      whyNow: "这是高金额后期商机，本周不干预会直接影响季度预测可信度。",
      impactLabel: "影响金额",
      impactValue: "CNY 4,080,000",
      ownerRole: "manager",
      ownerName: "刘建明",
      targetRole: "rep",
      targetName: "顾景行",
      status: "assigned",
      dueLabel: "48 小时内",
      priority: 88,
      confidence: 0.74,
      dataFreshness: "stale",
      coverage: 0.64,
      trustNote: "CRM 数据滞后，但会议纪要和主管汇报口径一致。",
      reasonItems: [
        "后期 deal 仍然没有真正的高层赞助。",
        "采购顾虑连续两次会议都没有被收口。",
      ],
      lineageId: "lineage-xuanhe",
      sourceKind: "report_snapshot",
      sourceIds: ["rep-report-rep-3", "meeting-2"],
      evidenceIds: ["evidence-1", "evidence-2"],
      accountIds: ["acc-3"],
      dealIds: ["deal-2"],
      meetingIds: ["meeting-2"],
      isVisible: true,
      canAssign: true,
      canEscalate: true,
      canRevoke: true,
      canDrillDown: true,
      availableActions: [
        { kind: "escalate", label: "升级 CEO", nextStatus: "escalated" },
        {
          kind: "revoke",
          label: "撤销任务",
          nextStatus: "revoked",
          revokeCardIds: ["rep-card-2"],
        },
      ],
    },
    {
      id: "manager-card-3",
      level: "manager",
      cardType: "manager_intervention",
      escalationCategory: null,
      upgradeReason: null,
      title: "广州大臣信息科技有限公司需要王豪给出试点报价边界",
      summary:
        "如果月底广州会要继续推进小游戏线试点，刘建明需要先拿到 CEO 对试点报价边界的明确授权，避免现场只聊价值不敢给边界。",
      recommendedAction: "正式上报王豪，请 CEO 决定试点报价边界能否放开。",
      whyNow: "客户当前真正缺的是‘能不能试’的边界，而不是更长的产品介绍。",
      impactLabel: "升级目标",
      impactValue: "CEO 决定试点报价边界",
      ownerRole: "manager",
      ownerName: "刘建明",
      targetRole: "ceo",
      targetName: "王豪",
      status: "escalated",
      dueLabel: "本周内",
      priority: 85,
      confidence: 0.66,
      dataFreshness: "fresh",
      coverage: 0.75,
      trustNote: "这是在真实会议基础上的编排动作，不是录音里已经发生的正式审批事实。",
      reasonItems: [
        "产品能力已被认可，但组织替换成本仍高。",
        "月底广州会需要一个更明确的试点边界才能继续推进。",
      ],
      lineageId: "lineage-dachen-pricing",
      sourceKind: "report_snapshot",
      sourceIds: ["rep-report-rep-2", "meeting-real-5"],
      evidenceIds: ["evidence-real-5"],
      accountIds: ["acc-real-5"],
      dealIds: ["deal-real-5"],
      meetingIds: ["meeting-real-5"],
      isVisible: true,
      canAssign: false,
      canEscalate: false,
      canRevoke: false,
      canDrillDown: true,
      availableActions: [],
    },
    {
      id: "manager-card-4",
      level: "manager",
      cardType: "manager_intervention",
      escalationCategory: null,
      upgradeReason: null,
      title: "王豪已批准大臣试点报价边界，刘建明需回收客户确认",
      summary:
        "CEO 已给出试点边界，下一步不再是内部讨论，而是让刘建明推动杨文星在月底广州会前回收客户明确反馈。",
      recommendedAction: "把已批准边界同步给杨文星，并要求在广州会前回收客户确认。",
      whyNow: "CEO 决策已经给出，组织动作必须立即落到团队执行。",
      impactLabel: "当前动作",
      impactValue: "把 CEO 决策转成客户确认",
      ownerRole: "manager",
      ownerName: "刘建明",
      targetRole: "rep",
      targetName: "杨文星",
      status: "received",
      dueLabel: "广州会前",
      priority: 78,
      confidence: 0.82,
      dataFreshness: "fresh",
      coverage: 0.75,
      trustNote: "这是 CEO 批准后真实生成的下游卡，不是假装已执行的状态。",
      reasonItems: [
        "CEO 已完成内部边界判断。",
        "现在只剩客户是否接受这条试点路径。",
      ],
      lineageId: "lineage-dachen-pricing",
      sourceKind: "executive_decision",
      sourceIds: ["ceo-card-2"],
      evidenceIds: ["evidence-real-5"],
      accountIds: ["acc-real-5"],
      dealIds: ["deal-real-5"],
      meetingIds: ["meeting-real-5"],
      isVisible: false,
      canAssign: true,
      canEscalate: false,
      canRevoke: false,
      canDrillDown: true,
      availableActions: [],
    },
    {
      id: "ceo-card-1",
      level: "ceo",
      cardType: "ceo_escalation",
      escalationCategory: "resource_dispatch",
      upgradeReason: "model_suggested",
      title: "广州紫菲网络科技有限公司建议王豪判断是否调售前资源",
      summary:
        "紫菲不是要 CEO 直接救火，而是要判断这次二访是否值得提前把售前资源压上去，帮助杨文星把试点切口做实。",
      recommendedAction: "决定是否让售前顾问加入杨文星的二访阵容。",
      whyNow: "紫菲是当前最像真实试点窗口的一条线，提前调资源的价值高于事后补救。",
      impactLabel: "CEO 决策",
      impactValue: "是否追加售前资源",
      ownerRole: "ceo",
      ownerName: "王豪",
      targetRole: "manager",
      targetName: "刘建明",
      status: "escalated",
      dueLabel: "今天内",
      priority: 98,
      confidence: 0.74,
      dataFreshness: "fresh",
      coverage: 0.82,
      trustNote: "升级来自模型建议，依据是会后切口明确、窗口短、且需要主管层编排阵容。",
      reasonItems: [
        "紫菲是这批真实会里最清晰的一条试点窗口。",
        "调资源的收益主要是把二访做成，而不是补救风险。",
      ],
      lineageId: "lineage-zifei",
      sourceKind: "escalation",
      sourceIds: ["manager-card-1"],
      evidenceIds: ["evidence-real-1"],
      accountIds: ["acc-real-1"],
      dealIds: ["deal-real-1"],
      meetingIds: ["meeting-real-1"],
      isVisible: true,
      canAssign: false,
      canEscalate: false,
      canRevoke: true,
      canDrillDown: true,
      availableActions: [
        { kind: "approve", label: "批准资源调度", nextStatus: "resolved" },
        { kind: "request_info", label: "要求补充信息", nextStatus: "returned" },
      ],
    },
    {
      id: "ceo-card-2",
      level: "ceo",
      cardType: "ceo_escalation",
      escalationCategory: "pricing_approval",
      upgradeReason: "user_reported",
      title: "广州大臣信息科技有限公司的试点报价边界待王豪批准",
      summary:
        "刘建明已正式上报：如果月底广州会要继续推进小游戏线试点，需要 CEO 先给出试点报价边界。",
      recommendedAction: "决定是否允许按试点口径给出更灵活的报价边界。",
      whyNow: "这是把认可产品能力变成可继续推进的关键一步，不然广州会容易继续停在抽象价值讨论。",
      impactLabel: "CEO 决策",
      impactValue: "批准 / 拒绝试点报价边界",
      ownerRole: "ceo",
      ownerName: "王豪",
      targetRole: "manager",
      targetName: "刘建明",
      status: "escalated",
      dueLabel: "本周内",
      priority: 92,
      confidence: 0.68,
      dataFreshness: "fresh",
      coverage: 0.75,
      trustNote: "这是主管主动上报的管理动作，不是原始会议里已经谈妥的商业事实。",
      reasonItems: [
        "客户目前的阻力是能不能试，而不是看不懂产品能力。",
        "没有 CEO 边界，主管和销售很难在广州会前做出有效推进。",
      ],
      lineageId: "lineage-dachen-pricing",
      sourceKind: "escalation",
      sourceIds: ["manager-card-3"],
      evidenceIds: ["evidence-real-5"],
      accountIds: ["acc-real-5"],
      dealIds: ["deal-real-5"],
      meetingIds: ["meeting-real-5"],
      isVisible: true,
      canAssign: false,
      canEscalate: false,
      canRevoke: true,
      canDrillDown: true,
      availableActions: [
        {
          kind: "approve",
          label: "批准报价边界",
          nextStatus: "resolved",
          revealCardIds: ["manager-card-4"],
        },
        { kind: "request_info", label: "要求补充信息", nextStatus: "returned" },
      ],
    },
    {
      id: "ceo-card-3",
      level: "ceo",
      cardType: "ceo_escalation",
      escalationCategory: "executive_intervention",
      upgradeReason: "model_suggested",
      title: "广州大可玩网络科技有限公司是否需要王豪亲自背书试用",
      summary:
        "这条线不是最高优先，但如果老板已经愿意比较方案，CEO 是否背书会影响客户把它看成普通交流还是正式试用判断。",
      recommendedAction: "决定是否由王豪在关键节点给一次试用背书。",
      whyNow: "大可玩的窗口更像老板判断型窗口，高层背书能否缩短试用决策值得被单独判断。",
      impactLabel: "CEO 选择",
      impactValue: "是否亲自背书试用",
      ownerRole: "ceo",
      ownerName: "王豪",
      targetRole: "manager",
      targetName: "刘建明",
      status: "reviewed",
      dueLabel: "本周内",
      priority: 76,
      confidence: 0.64,
      dataFreshness: "fresh",
      coverage: 0.78,
      trustNote: "升级来自模型建议，主要依据是老板型决策链短，背书动作可能直接改变推进速度。",
      reasonItems: [
        "客户当前更像在比方案和试用路径，而不是继续泛泛交流。",
        "老板型团队的关键节点容易被高层背书放大。",
      ],
      lineageId: "lineage-dakewan",
      sourceKind: "escalation",
      sourceIds: ["meeting-real-2", "rep-report-rep-2"],
      evidenceIds: ["evidence-real-2"],
      accountIds: ["acc-real-2"],
      dealIds: ["deal-real-2"],
      meetingIds: ["meeting-real-2"],
      isVisible: true,
      canAssign: false,
      canEscalate: false,
      canRevoke: false,
      canDrillDown: true,
      availableActions: [{ kind: "approve", label: "亲自介入", nextStatus: "resolved" }],
    },
    {
      id: "ceo-card-4",
      level: "ceo",
      cardType: "ceo_escalation",
      escalationCategory: "other",
      upgradeReason: "model_suggested",
      title: "其他：新美星空（北京）数字科技有限公司需要王豪指定关系维护 owner",
      summary:
        "这条线短期不是成交题，而是谁来长期维护高质量交流的组织题；如果没人明确 owner，关系价值会被自然消耗掉。",
      recommendedAction: "指定一个长期 owner，按关系维护而不是标准成交节奏经营新美星空。",
      whyNow: "当前最怕的不是没成交，而是误用标准销售动作把这类成熟自建客户推远。",
      impactLabel: "CEO 决策",
      impactValue: "指定关系维护 owner",
      ownerRole: "ceo",
      ownerName: "王豪",
      targetRole: "manager",
      targetName: "刘建明",
      status: "suggested",
      dueLabel: "本周内",
      priority: 70,
      confidence: 0.61,
      dataFreshness: "fresh",
      coverage: 0.62,
      trustNote: "不属于资源、报价或 CEO 亲自出面，但已经构成需要高层明确 owner 的组织问题。",
      reasonItems: [
        "新美星空当前更适合关系维护，而不是强推成交。",
        "如果没有明确 owner，这类关系价值通常会在日常跟进里被稀释。",
      ],
      lineageId: "lineage-newstar-owner",
      sourceKind: "escalation",
      sourceIds: ["meeting-real-6", "rep-report-rep-2"],
      evidenceIds: ["evidence-real-6"],
      accountIds: ["acc-real-6"],
      dealIds: ["deal-real-6"],
      meetingIds: ["meeting-real-6"],
      isVisible: true,
      canAssign: false,
      canEscalate: false,
      canRevoke: false,
      canDrillDown: true,
      availableActions: [{ kind: "approve", label: "指定 owner", nextStatus: "resolved" }],
    },
  ],
  assignments: [
    {
      id: "assignment-1",
      upstreamCardId: "manager-card-2",
      downstreamCardId: "rep-card-2",
      assignedByRole: "manager",
      assignedByName: "刘建明",
      assignedToRole: "rep",
      assignedToName: "顾景行",
      assignedAt: "2026-03-09T09:10:00+08:00",
      status: "active",
      revokeReason: null,
    },
  ],
  lineages: [
    {
      id: "lineage-zifei",
      cardId: "rep-card-1",
      parentCardIds: [],
      sourceCardIds: [],
      childCardIds: ["manager-card-1", "ceo-card-1"],
      meetingIds: ["meeting-real-1"],
      dealIds: ["deal-real-1"],
      accountIds: ["acc-real-1"],
      accountThreadIds: [accountThreadIds.zifei],
      evidenceIds: ["evidence-real-1"],
    },
    {
      id: "lineage-zifei",
      cardId: "manager-card-1",
      parentCardIds: ["rep-card-1"],
      sourceCardIds: ["rep-card-1"],
      childCardIds: ["ceo-card-1"],
      meetingIds: ["meeting-real-1"],
      dealIds: ["deal-real-1"],
      accountIds: ["acc-real-1"],
      accountThreadIds: [accountThreadIds.zifei],
      evidenceIds: ["evidence-real-1"],
    },
    {
      id: "lineage-zifei",
      cardId: "ceo-card-1",
      parentCardIds: ["manager-card-1"],
      sourceCardIds: ["manager-card-1"],
      childCardIds: [],
      meetingIds: ["meeting-real-1"],
      dealIds: ["deal-real-1"],
      accountIds: ["acc-real-1"],
      accountThreadIds: [accountThreadIds.zifei],
      evidenceIds: ["evidence-real-1"],
    },
    {
      id: "lineage-xuanhe",
      cardId: "rep-card-2",
      parentCardIds: ["manager-card-2"],
      sourceCardIds: ["manager-card-2"],
      childCardIds: [],
      meetingIds: ["meeting-2"],
      dealIds: ["deal-2"],
      accountIds: ["acc-3"],
      accountThreadIds: [accountThreadIds.xuanhe],
      evidenceIds: ["evidence-1", "evidence-2"],
    },
    {
      id: "lineage-xuanhe",
      cardId: "manager-card-2",
      parentCardIds: [],
      sourceCardIds: ["rep-card-2"],
      childCardIds: ["rep-card-2"],
      meetingIds: ["meeting-2"],
      dealIds: ["deal-2"],
      accountIds: ["acc-3"],
      accountThreadIds: [accountThreadIds.xuanhe],
      evidenceIds: ["evidence-1", "evidence-2"],
    },
    {
      id: "lineage-dachen-pricing",
      cardId: "rep-card-3",
      parentCardIds: [],
      sourceCardIds: [],
      childCardIds: ["manager-card-3", "ceo-card-2", "manager-card-4"],
      meetingIds: ["meeting-real-5"],
      dealIds: ["deal-real-5"],
      accountIds: ["acc-real-5"],
      accountThreadIds: [accountThreadIds.dachen],
      evidenceIds: ["evidence-real-5"],
    },
    {
      id: "lineage-dachen-pricing",
      cardId: "manager-card-3",
      parentCardIds: ["rep-card-3"],
      sourceCardIds: ["rep-card-3"],
      childCardIds: ["ceo-card-2", "manager-card-4"],
      meetingIds: ["meeting-real-5"],
      dealIds: ["deal-real-5"],
      accountIds: ["acc-real-5"],
      accountThreadIds: [accountThreadIds.dachen],
      evidenceIds: ["evidence-real-5"],
    },
    {
      id: "lineage-dachen-pricing",
      cardId: "ceo-card-2",
      parentCardIds: ["manager-card-3"],
      sourceCardIds: ["manager-card-3"],
      childCardIds: ["manager-card-4"],
      meetingIds: ["meeting-real-5"],
      dealIds: ["deal-real-5"],
      accountIds: ["acc-real-5"],
      accountThreadIds: [accountThreadIds.dachen],
      evidenceIds: ["evidence-real-5"],
    },
    {
      id: "lineage-dachen-pricing",
      cardId: "manager-card-4",
      parentCardIds: ["ceo-card-2"],
      sourceCardIds: ["ceo-card-2"],
      childCardIds: [],
      meetingIds: ["meeting-real-5"],
      dealIds: ["deal-real-5"],
      accountIds: ["acc-real-5"],
      accountThreadIds: [accountThreadIds.dachen],
      evidenceIds: ["evidence-real-5"],
    },
    {
      id: "lineage-dakewan",
      cardId: "ceo-card-3",
      parentCardIds: [],
      sourceCardIds: [],
      childCardIds: [],
      meetingIds: ["meeting-real-2"],
      dealIds: ["deal-real-2"],
      accountIds: ["acc-real-2"],
      accountThreadIds: [accountThreadIds.dakewan],
      evidenceIds: ["evidence-real-2"],
    },
    {
      id: "lineage-yaoshi",
      cardId: "rep-card-4",
      parentCardIds: [],
      sourceCardIds: [],
      childCardIds: [],
      meetingIds: ["meeting-5"],
      dealIds: ["deal-5"],
      accountIds: ["acc-5"],
      accountThreadIds: [accountThreadId("acc-5")],
      evidenceIds: ["evidence-3"],
    },
    {
      id: "lineage-newstar-owner",
      cardId: "ceo-card-4",
      parentCardIds: [],
      sourceCardIds: [],
      childCardIds: [],
      meetingIds: ["meeting-real-6"],
      dealIds: ["deal-real-6"],
      accountIds: ["acc-real-6"],
      accountThreadIds: [accountThreadIds.newstar],
      evidenceIds: ["evidence-real-6"],
    },
  ],
  flowEvents: [
    {
      id: "flow-zifei-1",
      lineageId: "lineage-zifei",
      cardId: "rep-card-1",
      eventType: "meeting_ingested",
      actorLabel: "Task Router",
      role: "system",
      occurredAt: "2026-03-05T11:35:00+08:00",
      summary: "把杨文星 2026 年 3 月 3 日的紫菲拜访转成待确认判断。",
    },
    {
      id: "flow-zifei-2",
      lineageId: "lineage-zifei",
      cardId: "rep-card-1",
      eventType: "confirmed",
      actorLabel: "杨文星",
      role: "rep",
      occurredAt: "2026-03-05T12:00:00+08:00",
      summary: "确认紫菲需要在 1 周内完成二访。",
    },
    {
      id: "flow-zifei-3",
      lineageId: "lineage-zifei",
      cardId: "rep-card-1",
      eventType: "reported",
      actorLabel: "杨文星",
      role: "rep",
      occurredAt: "2026-03-05T12:10:00+08:00",
      summary: "把二访判断和问题清单上报给刘建明。",
    },
    {
      id: "flow-zifei-4",
      lineageId: "lineage-zifei",
      cardId: "manager-card-1",
      eventType: "reviewed",
      actorLabel: "刘建明",
      role: "manager",
      occurredAt: "2026-03-05T12:30:00+08:00",
      summary: "判断主管层要先锁二访阵容和材料，而不是继续追加摘要。",
    },
    {
      id: "flow-zifei-5",
      lineageId: "lineage-zifei",
      cardId: "ceo-card-1",
      eventType: "escalated",
      actorLabel: "刘建明",
      role: "manager",
      occurredAt: "2026-03-05T12:45:00+08:00",
      summary: "建议必要时由王豪判断是否给杨文星追加售前资源。",
    },
    {
      id: "flow-xuanhe-1",
      lineageId: "lineage-xuanhe",
      cardId: "manager-card-2",
      eventType: "assigned",
      actorLabel: "刘建明",
      role: "manager",
      occurredAt: "2026-03-09T09:10:00+08:00",
      summary: "把重建高层赞助任务正式派给顾景行。",
    },
    {
      id: "flow-xuanhe-2",
      lineageId: "lineage-xuanhe",
      cardId: "rep-card-2",
      eventType: "received",
      actorLabel: "Task Router",
      role: "system",
      occurredAt: "2026-03-09T09:10:01+08:00",
      summary: "让顾景行真实收到一张新的任务卡。",
    },
    {
      id: "flow-dachen-1",
      lineageId: "lineage-dachen-pricing",
      cardId: "rep-card-3",
      eventType: "meeting_ingested",
      actorLabel: "Task Router",
      role: "system",
      occurredAt: "2026-03-04T08:20:00+08:00",
      summary: "把广州大臣的会后判断转成待确认任务卡。",
    },
    {
      id: "flow-dachen-2",
      lineageId: "lineage-dachen-pricing",
      cardId: "rep-card-3",
      eventType: "confirmed",
      actorLabel: "杨文星",
      role: "rep",
      occurredAt: "2026-03-04T09:00:00+08:00",
      summary: "确认月底广州会必须收敛成小游戏线试点判断。",
    },
    {
      id: "flow-dachen-3",
      lineageId: "lineage-dachen-pricing",
      cardId: "rep-card-3",
      eventType: "reported",
      actorLabel: "杨文星",
      role: "rep",
      occurredAt: "2026-03-04T09:20:00+08:00",
      summary: "把需要老板与技术负责人同场的信息上报给刘建明。",
    },
    {
      id: "flow-dachen-4",
      lineageId: "lineage-dachen-pricing",
      cardId: "manager-card-3",
      eventType: "escalated",
      actorLabel: "刘建明",
      role: "manager",
      occurredAt: "2026-03-04T10:00:00+08:00",
      summary: "判断若要继续推进试点，必须先由王豪给出报价边界。",
    },
    {
      id: "flow-dakewan-1",
      lineageId: "lineage-dakewan",
      cardId: "ceo-card-3",
      eventType: "suggested",
      actorLabel: "Task Router",
      role: "system",
      occurredAt: "2026-03-05T05:05:00+08:00",
      summary: "根据大可玩老板型决策链，建议王豪评估是否需要高层背书。",
    },
    {
      id: "flow-yaoshi-1",
      lineageId: "lineage-yaoshi",
      cardId: "rep-card-4",
      eventType: "suggested",
      actorLabel: "Task Router",
      role: "system",
      occurredAt: "2026-03-01T18:00:00+08:00",
      summary: "由于缺少完整转录，只能给出低置信度的会后建议。",
    },
    {
      id: "flow-newstar-1",
      lineageId: "lineage-newstar-owner",
      cardId: "ceo-card-4",
      eventType: "suggested",
      actorLabel: "Task Router",
      role: "system",
      occurredAt: "2026-03-05T09:35:00+08:00",
      summary: "建议把新美星空从标准成交节奏切换成关系维护节奏。",
    },
  ],
};
