import { realMeetings } from "@/lib/mocks/yang-wenxing-real";

import type { ConversationSeed } from "@/lib/conversational-os/types";

const zifeiMeeting = realMeetings.find((meeting) => meeting.id === "meeting-real-1");
const dakewanMeeting = realMeetings.find((meeting) => meeting.id === "meeting-real-2");
const dachenMeeting = realMeetings.find((meeting) => meeting.id === "meeting-real-5");

if (!zifeiMeeting || !dakewanMeeting || !dachenMeeting) {
  throw new Error("Conversational Agent OS seed is missing required Yang Wenxing real meetings.");
}

export const defaultThreadId = "thread-rep-yang";

export const conversationSeed: ConversationSeed = {
  threads: [
    {
      id: "thread-rep-yang",
      title: "杨文星私有群",
      description: "杨文星、一线销售 AgentBP 与主管 Agent 的协作线程。",
      threadType: "rep_private",
      primaryRole: "rep",
      pinnedCardId: "card-rep-zifei-priority",
    },
    {
      id: "thread-manager-liu",
      title: "刘建明主管群",
      description: "刘建明、主管 AgentBP 与 CEO Agent 的升级与编排线程。",
      threadType: "manager_private",
      primaryRole: "manager",
      pinnedCardId: "card-manager-zifei-intervention",
    },
    {
      id: "thread-ceo-wang",
      title: "王豪 CEO 线程",
      description: "王豪与 CEO Admin Agent 的高层决策线程。",
      threadType: "ceo_private",
      primaryRole: "ceo",
      pinnedCardId: "card-ceo-dachen-pricing",
    },
  ],
  members: [
    {
      id: "member-rep-human-yang",
      threadId: "thread-rep-yang",
      actorId: "human-yang",
      actorName: "杨文星",
      memberType: "human_rep",
      role: "rep",
    },
    {
      id: "member-rep-agent-bp",
      threadId: "thread-rep-yang",
      actorId: "agent-rep-bp",
      actorName: "一线销售 AgentBP",
      memberType: "agent_rep_bp",
      role: "agent",
    },
    {
      id: "member-manager-agent-in-rep",
      threadId: "thread-rep-yang",
      actorId: "agent-manager-bp",
      actorName: "主管 Agent",
      memberType: "agent_manager_bp",
      role: "agent",
    },
    {
      id: "member-manager-human-liu",
      threadId: "thread-manager-liu",
      actorId: "human-liu",
      actorName: "刘建明",
      memberType: "human_manager",
      role: "manager",
    },
    {
      id: "member-manager-agent-bp",
      threadId: "thread-manager-liu",
      actorId: "agent-manager-bp",
      actorName: "主管 AgentBP",
      memberType: "agent_manager_bp",
      role: "agent",
    },
    {
      id: "member-ceo-agent-in-manager",
      threadId: "thread-manager-liu",
      actorId: "agent-ceo-admin",
      actorName: "CEO Agent",
      memberType: "agent_ceo_admin",
      role: "agent",
    },
    {
      id: "member-ceo-human-wang",
      threadId: "thread-ceo-wang",
      actorId: "human-wang",
      actorName: "王豪",
      memberType: "human_ceo",
      role: "ceo",
    },
    {
      id: "member-ceo-agent-admin",
      threadId: "thread-ceo-wang",
      actorId: "agent-ceo-admin",
      actorName: "CEO Admin Agent",
      memberType: "agent_ceo_admin",
      role: "agent",
    },
  ],
  messages: [
    {
      id: "msg-rep-yang-1",
      threadId: "thread-rep-yang",
      actorId: "human-yang",
      actorName: "杨文星",
      kind: "source_input",
      body: "刚见完客户，我先把原始材料发进来，你帮我整理成可上报的摘要和卡片。",
      occurredAt: "2026-03-05T19:09:00+08:00",
      visibility: "visible_to_thread",
      relatedCardId: null,
      sourceItems: [
        {
          kind: "meeting_summary",
          title: "硬件会议摘要",
          detail: `${zifeiMeeting.title}，来自现场硬件转录与结构化总结。`,
        },
        {
          kind: "audio",
          title: "现场录音",
          detail: "客户拜访结束后上传，包含对 VOD 聚合 API 和降本诉求的原始表达。",
        },
        {
          kind: "screenshot",
          title: "微信截图",
          detail: "会后补充了云游戏、AI 视频和试点边界问题。",
        },
        {
          kind: "link",
          title: "会议详情链接",
          detail: `/meetings/${zifeiMeeting.id}`,
        },
      ],
    },
    {
      id: "msg-rep-yang-2",
      threadId: "thread-rep-yang",
      actorId: "agent-rep-bp",
      actorName: "一线销售 AgentBP",
      kind: "agent_reply",
      body: "收到，你先不用自己整理。我先基于原始材料做归纳，再把你需要确认的摘要和推进卡发回来。",
      occurredAt: "2026-03-05T19:10:00+08:00",
      visibility: "visible_to_thread",
      relatedCardId: null,
    },
    {
      id: "msg-rep-yang-3",
      threadId: "thread-rep-yang",
      actorId: "agent-rep-bp",
      actorName: "一线销售 AgentBP",
      kind: "agent_reply",
      body: "我已经把重点收束成一张推进卡，核心不是继续讲产品，而是 1 周内锁定二访阵容和试点问题清单。",
      occurredAt: "2026-03-05T19:11:00+08:00",
      visibility: "visible_to_thread",
      relatedCardId: "card-rep-zifei-priority",
    },
    {
      id: "msg-rep-yang-4",
      threadId: "thread-rep-yang",
      actorId: "agent-manager-bp",
      actorName: "主管 Agent",
      kind: "system_handoff",
      body: "你的信息我已经收到，处理完会把需要你知道的结果摘要回传给你。",
      occurredAt: "2026-03-05T19:12:00+08:00",
      visibility: "visible_to_thread",
      relatedCardId: null,
    },
    {
      id: "msg-rep-yang-daily-brief",
      threadId: "thread-rep-yang",
      actorId: "agent-rep-bp",
      actorName: "一线销售 AgentBP",
      kind: "agent_reply",
      body: "今天你需要重点关注 3 件事：\n1. 紫菲二访阵容锁定（剩余窗口 5 天）\n2. 大可玩方案对比试点跟进（客户上周提了新需求）\n3. 大臣小游戏试点的报价边界确认（CEO 侧已批准）\n\n以下是每件事的详细卡片，你可以逐个确认或追问。",
      occurredAt: "2026-03-06T09:00:00+08:00",
      visibility: "visible_to_thread",
      relatedCardId: null,
    },
    {
      id: "msg-rep-yang-card-dakewan",
      threadId: "thread-rep-yang",
      actorId: "agent-rep-bp",
      actorName: "一线销售 AgentBP",
      kind: "agent_reply",
      body: "大可玩上周二访后提了两个新需求点，需要你在本周内给出答复方案。",
      occurredAt: "2026-03-06T09:01:00+08:00",
      visibility: "visible_to_thread",
      relatedCardId: "card-rep-dakewan-followup",
    },
    {
      id: "msg-rep-yang-card-dachen",
      threadId: "thread-rep-yang",
      actorId: "agent-rep-bp",
      actorName: "一线销售 AgentBP",
      kind: "agent_reply",
      body: "大臣小游戏试点边界 CEO 已批准，你现在可以准备试点方案并联系客户确认时间。",
      occurredAt: "2026-03-06T09:02:00+08:00",
      visibility: "visible_to_thread",
      relatedCardId: "card-rep-dachen-trial",
    },
    {
      id: "msg-manager-liu-1",
      threadId: "thread-manager-liu",
      actorId: "agent-manager-bp",
      actorName: "主管 AgentBP",
      kind: "agent_reply",
      body: "我已接收杨文星关于紫菲二访的上报，当前需要先确定二访阵容，并准备是否上升到 CEO 层看报价边界与资源调度。",
      occurredAt: "2026-03-05T19:15:00+08:00",
      visibility: "visible_to_thread",
      relatedCardId: "card-manager-zifei-intervention",
    },
    {
      id: "msg-ceo-wang-1",
      threadId: "thread-ceo-wang",
      actorId: "agent-ceo-admin",
      actorName: "CEO Admin Agent",
      kind: "agent_reply",
      body: `${dachenMeeting.title} 的摘要已整理完成。你现在看到的是升级摘要和待决策卡，默认不展示下层原始处理细节。`,
      occurredAt: "2026-03-05T19:20:00+08:00",
      visibility: "visible_to_thread",
      relatedCardId: "card-ceo-dachen-pricing",
    },
  ],
  cards: [
    {
      id: "card-rep-zifei-priority",
      threadId: "thread-rep-yang",
      title: "广州紫菲网络科技有限公司需要 1 周内锁定二访阵容",
      summary: "先把二访问题收束成 VOD 聚合 API、云游戏、AI 视频和降本边界，不再泛泛讲整体替换。",
      detail:
        "这张卡只保留一个主决策：先把二访定下来。杨文星当前最重要的不是继续解释产品，而是把参会人、问题清单和试点材料在 1 周内收齐。",
      trustNote: "来源于杨文星真实会议材料与会后跟进判断。",
      priorityRank: 100,
      primaryAction: "confirm",
      primaryActionLabel: "确认并上报",
      sourceMeetingId: "meeting-real-1",
      sourceDealId: "deal-real-1",
      createdAt: "2026-03-05T19:11:00+08:00",
    },
    {
      id: "card-rep-dakewan-followup",
      threadId: "thread-rep-yang",
      title: "大可玩新需求跟进：本周内回复方案对比结果",
      summary: "客户上周二访后追加了归因精度和素材审核效率两个需求点，需要你在周五前给出对比方案。",
      detail:
        "大可玩创始人直接参与决策，对竞品痛点认知清晰。本次跟进的关键是拿出我们在归因精度和素材审核上的数据对比，而不是泛泛讲功能清单。",
      trustNote: "来源于大可玩二访后微信沟通整理。",
      priorityRank: 95,
      primaryAction: "confirm",
      primaryActionLabel: "确认跟进计划",
      sourceMeetingId: "meeting-real-2",
      sourceDealId: "deal-real-2",
      createdAt: "2026-03-06T09:01:00+08:00",
    },
    {
      id: "card-rep-dachen-trial",
      threadId: "thread-rep-yang",
      title: "大臣小游戏试点：CEO 已批准报价边界，准备试点方案",
      summary: "试点边界已获批，现在需要准备详细的试点技术方案和时间表，联系客户确认启动时间。",
      detail:
        "CEO 王豪已批准小游戏线试点的报价边界。你的下一步是在本周内准备技术试点方案（含接入方式、数据验证标准和成功指标），并与大臣方确认 3 月底前启动。",
      trustNote: "来源于 CEO 决策回传，边界已正式批准。",
      priorityRank: 90,
      primaryAction: "confirm",
      primaryActionLabel: "确认并开始准备",
      sourceMeetingId: "meeting-real-5",
      sourceDealId: "deal-real-5",
      createdAt: "2026-03-06T09:02:00+08:00",
    },
    {
      id: "card-manager-zifei-intervention",
      threadId: "thread-manager-liu",
      title: "刘建明需要决定紫菲二访阵容是否上升到高层支持",
      summary: "主管当前要做的是编排资源，而不是重复看会议摘要。",
      detail:
        "杨文星已经把紫菲切口收窄。主管需要在这个节点判断：先由自己完成阵容编排，还是在需要额外售前/边界判断时上升到 CEO 层。",
      trustNote: "下游只能看到摘要，不会看到上层 Agent 内部完整对话。",
      priorityRank: 96,
      primaryAction: "report_upstream",
      primaryActionLabel: "升级给 CEO",
      sourceMeetingId: "meeting-real-1",
      sourceDealId: "deal-real-1",
      createdAt: "2026-03-05T19:15:00+08:00",
    },
    {
      id: "card-ceo-dachen-pricing",
      threadId: "thread-ceo-wang",
      title: "王豪需要决定广州大臣小游戏试点报价边界",
      summary: "CEO 默认只消费升级摘要、待决策卡和决策结果；需要时再下钻到真实证据。",
      detail:
        "月底广州会是否能继续推进，关键在于 CEO 是否愿意先给出小游戏线试点的报价边界。详情里可以继续下钻到相关会议、Deal 和证据。",
      trustNote: "此卡来自主管层升级摘要，不暴露下游内部处理全文。",
      priorityRank: 98,
      primaryAction: "approve",
      primaryActionLabel: "批准边界",
      sourceMeetingId: "meeting-real-5",
      sourceDealId: "deal-real-5",
      createdAt: "2026-03-05T19:20:00+08:00",
    },
  ],
  handoffs: [
    {
      id: "handoff-rep-to-manager-zifei",
      fromThreadId: "thread-rep-yang",
      toThreadId: "thread-manager-liu",
      summary: "杨文星的紫菲二访判断已整理为主管摘要。",
      detailVisibleToDownstream: false,
      createdAt: "2026-03-05T19:13:00+08:00",
      relatedCardId: "card-rep-zifei-priority",
    },
    {
      id: "handoff-manager-to-ceo-dachen",
      fromThreadId: "thread-manager-liu",
      toThreadId: "thread-ceo-wang",
      summary: "广州大臣小游戏试点边界问题已升级给 CEO Admin Agent。",
      detailVisibleToDownstream: false,
      createdAt: "2026-03-05T19:18:00+08:00",
      relatedCardId: "card-ceo-dachen-pricing",
    },
  ],
  deliveries: [
    {
      id: "delivery-rep-to-manager-zifei",
      fromThreadId: "thread-rep-yang",
      toThreadId: "thread-manager-liu",
      deliveryType: "report_upstream",
      summary: "杨文星的紫菲二访判断已整理为主管摘要。",
      createdAt: "2026-03-05T19:13:00+08:00",
      relatedCardId: "card-rep-zifei-priority",
    },
    {
      id: "delivery-manager-to-ceo-dachen",
      fromThreadId: "thread-manager-liu",
      toThreadId: "thread-ceo-wang",
      deliveryType: "escalate_upstream",
      summary: "广州大臣小游戏试点边界问题已升级给 CEO Admin Agent。",
      createdAt: "2026-03-05T19:18:00+08:00",
      relatedCardId: "card-ceo-dachen-pricing",
    },
  ],
  readStates: [
    {
      threadId: "thread-rep-yang",
      lastReadAt: "2026-03-05T19:12:00+08:00",
    },
    {
      threadId: "thread-manager-liu",
      lastReadAt: "2026-03-05T19:15:00+08:00",
    },
    {
      threadId: "thread-ceo-wang",
      lastReadAt: "2026-03-05T19:20:00+08:00",
    },
  ],
};
